CREATE DATABASE SALES_DB;
USE SALES_DB;
SELECT * FROM STORES;

#Task3
#Inner Join for Order Details 
#Join orders, order_items, and products to display detailed line items. 
SELECT * FROM ORDERS;
SELECT * FROM ORDER_ITEMS;
SELECT * FROM PRODUCTS;
SELECT orders.Order_Id,orders.Customer_Id,products.Product_Id,products.Product_Name,products.Model_Year,order_items.List_Price,order_items.Discount,
order_items.Quantity,order_items.Total_Price,orders.Order_Date,orders.Required_Date,orders.Shipped_Date,orders.Order_status
FROM orders INNER JOIN order_items ON orders.Order_Id = order_items.Order_Id
INNER JOIN products ON products.Product_Id = order_items.Product_Id
ORDER BY order_id;

#Task 4
#Total Sales by Store 
#Write a query to group sales (total_price) by each store_id. 

SELECT orders.Store_id, sum(order_items.Total_Price) AS TotalSales FROM order_items JOIN orders ON orders.Order_Id=Order_items.Order_Id
GROUP BY orders.Store_id; 
SELECT O.STORE_ID,SUM(OI.TOTAL_PRICE) AS TOTALSALES
FROM ORDERS AS O JOIN ORDER_ITEMS AS OI ON O.ORDER_ID=OI.ORDER_ID
group by O.STORE_ID;


#Task 5
#Top 5 Selling Products 
#Use ORDER BY and LIMIT to get the top 5 most sold products by quantity
SELECT p.Product_Id,p.Product_Name,SUM(oi.Quantity) AS TotalQuantitySold
FROM order_items AS oi
JOIN products AS p ON oi.Product_Id = p.Product_Id
GROUP BY p.Product_Id, p.Product_Name
ORDER BY TotalQuantitySold DESC
LIMIT 5;	

#Task6
#Customer Purchase Summary 
#For each customer, return total orders placed, total items purchased,and total revenue. 
SELECT * FROM ORDERS;
SELECT * FROM ORDER_ITEMS;
SELECT * FROM CUSTOMERS;
SELECT C.CUSTOMER_ID,C.CUSTOMER_NAME,count(distinct(O.ORDER_ID)) AS TotalOrder,sum(OI.QUANTITY)AS TotalItems,
sum(oi.total_price) as TotalRevenue
FROM CUSTOMERS AS C
JOIN ORDERS AS O ON C.CUSTOMER_ID=O.CUSTOMER_ID
JOIN ORDER_ITEMS AS OI ON O.ORDER_ID=OI.ORDER_ID
GROUP BY C.CUSTOMER_ID,C.CUSTOMER_NAME;

#Task 7
#Segment Customers by Total Spend
#Write a query to classify customers into spending brackets (e.g., low, medium, high). 
SELECT C.Customer_Name,C.Customer_Id,
sum(OI.total_price) AS TotalSpend,
case
WHEN(OI.Total_Price)<200 THEN "LOW"
when(OI.Total_Price) BETWEEN 200 AND 300 THEN "MEDIUM"
ELSE "HIGH"
END AS SpendingBrackets
FROM CUSTOMERS AS C JOIN ORDERS AS O ON C.Customer_ID=O.Customer_ID
JOIN ORDER_ITEMS AS OI ON O.Order_Id=OI.Order_Id
GROUP BY C.Customer_Name,C.Customer_Id,Total_Price
ORDER BY TotalSpend asc;	

#Task8
#Staff Performance Analysis 
#Analyze total revenue generated by each staff member based on their handled orders. 
SELECT * FROM STAFFS;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_ITEMS;
select staffs.Staff_Id,staffs.staff_name,sum(order_items.total_price) total_revenue
FROM staffs LEFT JOIN orders ON orders.staff_id=staffs.Staff_Id
LEFT JOIN order_items ON order_items.Order_Id=orders.order_Id
GROUP BY Staff_Name,Staff_Id;

#Tak9
#Stock Alert Query
#Write a query to list products where stock quantity < 10 in any store.
SELECT * FROM PRODUCTS;
SELECT * FROM STOCKS;
SELECT * FROM STORES;
SELECT P.Product_Id,P.Product_Name,SO.Quantity,st.Store_Name,st.Store_Id
FROM Products as P JOIN STOCKS AS SO ON SO.Product_Id=p.Product_Id
JOIN stores as st ON st.Store_Id=SO.Store_Id
WHERE SO.Quantity <10;

